### ISSUE TITLE
请问如何debug下每次中间是哪些token位置被选中进行拼接的？

### ISSUE THREAD

**Issue by yinochaos** [thunlp/InfLLM#27]
RT
请问如何debug下每次中间是哪些token位置被选中进行拼接的？能否告诉下相关代码的位置

**Comment by guyan364** [comment]
你可以查看 get block topk 的输出 https://github.com/thunlp/InfLLM/blob/main/inf_llm/attention/context_manager.py#L366，
位置即为 [n_init + id * block_size, n_init + id * block_size + block_size]
