### ISSUE TITLE
qwen系列模型支持

### ISSUE THREAD

**Issue by fst813** [thunlp/InfLLM#3]
能否支持下qwen系列模型

**Comment by huliangbing** [comment]
同问

**Comment by NaivePawn** [comment]
@fst813 我在patch.py里加了这一段，不知道对不对，实验下来点没降
![image](https://github.com/thunlp/InfLLM/assets/34669331/0598c660-aa38-4cb9-bf1a-f8f442570d87)

**Comment by fst813** [comment]
@NaivePawn 只加这个不对吧？你跑起来了？

**Comment by NaivePawn** [comment]
> @NaivePawn 只加这个不对吧？你跑起来了？

啥不对？我跑起来了，要用qwen1.5那个

**Comment by fst813** [comment]
我跑的不是1.5 跑的qwen，改了很多东西

**Comment by huliangbing** [comment]
效果如何？
